### ISSUE TITLE
Links on the attributions page don't work

### ISSUE THREAD

**Issue by ChristopherLlewellyn** [battle-buddy/battlebuddy-android#13]
**Describe the bug**
Tapping any of the links on the attributions page don't take you anywhere. Nothing happens when tapping them.

**To Reproduce**
1. Go to the attributions page
2. Click on any of the links

**Expected behavior**
The link should open the URL in a web browser.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE
 - OS: Android 11
 - Browser: Brave
 - Version: 1.2.4 (47)

**Comment by morphy2k** [comment]
Just the ones on the attributions page or all links like the GitHub link on the **More** page?

**Comment by ChristopherLlewellyn** [comment]
Actually it's all links except for "Rate the app"

**Comment by kokarn** [comment]
Exact same behavior for me.

Samsung S21 Plus

**Comment by morphy2k** [comment]
> Exact same behavior for me.
> 
> Samsung S21 Plus

Which Android, browser and app version?

**Comment by kokarn** [comment]
> > Exact same behavior for me.
> > Samsung S21 Plus
> 
> Which Android, browser and app version?

Android: 11
Browser: Chrome 91
App version: 1.2.4 (47)

**Comment by LrdGrmRpr** [comment]
Same for me:
- Samsung S20 5G
- Android: 11
- One UI: 3.1
- App: 1.2.3 (44)
- Browser: Any, as doesn't trigger "open in browser" action

**Comment by morphy2k** [comment]
666a3b6 should fix it. See https://github.com/flutter/flutter/issues/63727
