### ISSUE TITLE
Ammo values are updated?

### ISSUE THREAD

**Issue by rubanunes** [battle-buddy/battlebuddy-android#15]
As most players tend to use NoFoodAfterMidnight's ammo chart so do I. After comparing the app's number against the sheet he provides they don't match. Is that normal? What source is used for those values? Thanks.

**Comment by morphy2k** [comment]
Can you please give an example where it doesn't match?

All data comes from one source, but is processed differently.

**Comment by rubanunes** [comment]
Yes. For example on the 5.45x39 ammo. On the BB we have BP with 35 Pen and 49 Damage and on the NFAM's sheets it's 34 and 48. Also the FMJ on that calibre is also not correct. They're minor values but nonetheless. Also it's weird why when comparing the higher values don't appear on top.

**Comment by morphy2k** [comment]
I just checked, NOFAM's table is outdated.
BB is automatically updated several times a day. So if you see other values somewhere, they are most likely not up to date. Our source is extremely reliable.
