### ISSUE TITLE
Price List doesn't populate on android

### ISSUE THREAD

**Issue by bwheatley** [battle-buddy/battlebuddy-android#3]
On App version 1.2.2

My buddy on IOS is not having the issue, while my other buddy on android is.

**Describe the bug**
Price List doesn't populate on android

**To Reproduce**
1. goto price listing it just spins and never returns any data.

**Expected behavior**
Prices

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 3XL
 - OS: Android 11
 - Browser N/A (using app)
 - Version 1.2.2

**Additional context**
My buddy has the same issue Android 10,  on Galaxy Note 9, using the latest app.

**Comment by bwheatley** [comment]
I must have missed it, when do you expect to release a new build to Google play store?

**Comment by bwheatley** [comment]
Thanks for the quick fix btw <3

**Comment by morphy2k** [comment]
> I must have missed it, when do you expect to release a new build to Google play store?

The new release (v1.2.3) is already live for over 20 hours.
